### ISSUE TITLE
customize image alignment

### ISSUE THREAD

**Issue by k4lizen** [gokarna-theme/gokarna-hugo#253]
Currently in posts images are center aligned. I'd much prefer if they were left aligned since thats how they are in other software I use for viewing .md files.

Is there a way to do this?

**Comment by k4lizen** [comment]
Oh I didnt think of that, thanks.
This seems to work:
```css
.post.container img {
  display: block;
  margin-left: 0;
  margin-right: auto;
}
```
